# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 16 May 2014 16:21:50 +0000
*               @ALL          8
admarch	@ALL	1
admsis	@ALL	1
archcen	@ALL	1
archcor	@ALL	1
archges	@ALL	1
archint	@ALL	1
desarrollo	@ALL	1
disenio	@ALL	1
instalacion	@ALL	1
start	@ALL	1
usuario	@ALL	1
